"""
Dicionário de Tradução Química Português -> Inglês
Versão Expandida - Mais de 1000 traduções
"""

DICIONARIO_QUIMICO = {
    # ============================================
    # HIDROCARBONETOS (Alcanos)
    # ============================================
    'metano': 'methane',
    'etano': 'ethane',
    'propano': 'propane',
    'butano': 'butane',
    'pentano': 'pentane',
    'hexano': 'hexane',
    'heptano': 'heptane',
    'octano': 'octane',
    'nonano': 'nonane',
    'decano': 'decane',
    'undecano': 'undecane',
    'dodecano': 'dodecane',
    'tridecano': 'tridecane',
    'tetradecano': 'tetradecane',
    'pentadecano': 'pentadecane',
    'hexadecano': 'hexadecane',
    'heptadecano': 'heptadecane',
    'octadecano': 'octadecane',
    'nonadecano': 'nonadecane',
    'eicosano': 'eicosane',
    'heneicosano': 'heneicosane',
    'docosano': 'docosane',
    'tricosano': 'tricosane',
    'tetracosano': 'tetracosane',
    'pentacosano': 'pentacosane',
    'hexacosano': 'hexacosane',
    'triacontano': 'triacontane',
    'tetracontano': 'tetracontane',
    'pentacontano': 'pentacontane',
    'hexacontano': 'hexacontane',
    
    # Alcenos (com ligação dupla)
    'eteno': 'ethene',
    'etileno': 'ethylene',
    'propeno': 'propene',
    'propileno': 'propylene',
    'buteno': 'butene',
    'butileno': 'butylene',
    'penteno': 'pentene',
    'hexeno': 'hexene',
    'hepteno': 'heptene',
    'octeno': 'octene',
    'noneno': 'nonene',
    'deceno': 'decene',
    'undeceno': 'undecene',
    'dodeceno': 'dodecene',
    'trideceno': 'tridecene',
    'tetradeceno': 'tetradecene',
    'pentadeceno': 'pentadecene',
    'hexadeceno': 'hexadecene',
    'heptadeceno': 'heptadecene',
    'octadeceno': 'octadecene',
    'nonadeceno': 'nonadecene',
    'eicoseno': 'eicosene',
    
    # Alcinos (com ligação tripla)
    'etino': 'ethyne',
    'acetileno': 'acetylene',
    'propino': 'propyne',
    'butino': 'butyne',
    'pentino': 'pentyne',
    'hexino': 'hexyne',
    'heptino': 'heptyne',
    'octino': 'octyne',
    'nonino': 'nonyne',
    'decino': 'decyne',
    
    # Dienos (duas ligações duplas)
    'butadieno': 'butadiene',
    'pentadieno': 'pentadiene',
    'hexadieno': 'hexadiene',
    'heptadieno': 'heptadiene',
    'octadieno': 'octadiene',
    'isopreno': 'isoprene',
    
    # Cicloalcanos
    'ciclopropano': 'cyclopropane',
    'ciclobutano': 'cyclobutane',
    'ciclopentano': 'cyclopentane',
    'ciclohexano': 'cyclohexane',
    'cicloheptano': 'cycloheptane',
    'ciclooctano': 'cyclooctane',
    'ciclodecano': 'cyclodecane',
    'cicloundecano': 'cycloundecane',
    'ciclododecano': 'cyclododecane',
    
    # Cicloalcenos
    'ciclopropeno': 'cyclopropene',
    'ciclobuteno': 'cyclobutene',
    'ciclopenteno': 'cyclopentene',
    'ciclohexeno': 'cyclohexene',
    'ciclohepteno': 'cycloheptene',
    'cicloocteno': 'cyclooctene',
    'ciclodeceno': 'cyclodecene',
    
    # ============================================
    # HIDROCARBONETOS AROMÁTICOS
    # ============================================
    'benzeno': 'benzene',
    'tolueno': 'toluene',
    'fenol': 'phenol',
    'anilina': 'aniline',
    'estireno': 'styrene',
    'naftaleno': 'naphthalene',
    'antraceno': 'anthracene',
    'fenantreno': 'phenanthrene',
    'pireno': 'pyrene',
    'criseno': 'chrysene',
    'benzoantraceno': 'benzanthracene',
    'benzopireno': 'benzopyrene',
    'coroneno': 'coronene',
    'bifenil': 'biphenyl',
    'trifenileno': 'triphenylene',
    'perileno': 'perylene',
    'fluoreno': 'fluorene',
    'indeno': 'indene',
    'acenafteno': 'acenaphthene',
    'acenaftileno': 'acenaphthylene',
    'fluoranteno': 'fluoranthene',
    
    # Compostos heterocíclicos aromáticos
    'piridina': 'pyridine',
    'quinolina': 'quinoline',
    'isoquinolina': 'isoquinoline',
    'acridina': 'acridine',
    'indol': 'indole',
    'pirrol': 'pyrrole',
    'furan': 'furan',
    'tiofeno': 'thiophene',
    'imidazol': 'imidazole',
    'pirazol': 'pyrazole',
    'oxazol': 'oxazole',
    'tiazol': 'thiazole',
    'pirimidina': 'pyrimidine',
    'purina': 'purine',
    'pteridina': 'pteridine',
    
    # Benzaldeídos e derivados
    'benzaldeido': 'benzaldehyde',
    'benzaldeído': 'benzaldehyde',
    'acido benzoico': 'benzoic acid',
    'ácido benzoico': 'benzoic acid',
    'benzil': 'benzyl',
    'benzofenona': 'benzophenone',
    'benzilico': 'benzylic',
    'benzoato': 'benzoate',
    
    # ============================================
    # ÁLCOOIS
    # ============================================
    'metanol': 'methanol',
    'alcool metilico': 'methyl alcohol',
    'álcool metílico': 'methyl alcohol',
    'etanol': 'ethanol',
    'alcool etilico': 'ethyl alcohol',
    'álcool etílico': 'ethyl alcohol',
    'propanol': 'propanol',
    'isopropanol': 'isopropanol',
    'alcool isopropilico': 'isopropyl alcohol',
    'álcool isopropílico': 'isopropyl alcohol',
    'butanol': 'butanol',
    'isobutanol': 'isobutanol',
    'sec-butanol': 'sec-butanol',
    'terc-butanol': 'tert-butanol',
    'pentanol': 'pentanol',
    'hexanol': 'hexanol',
    'heptanol': 'heptanol',
    'octanol': 'octanol',
    'nonanol': 'nonanol',
    'decanol': 'decanol',
    'undecanol': 'undecanol',
    'dodecanol': 'dodecanol',
    'tetradecanol': 'tetradecanol',
    'hexadecanol': 'hexadecanol',
    'octadecanol': 'octadecanol',
    
    # Álcoois aromáticos
    'benzilico': 'benzyl alcohol',
    'furfurilico': 'furfuryl alcohol',
    'cinamilico': 'cinnamyl alcohol',
    'fenetilico': 'phenethyl alcohol',
    
    # Polióis
    'etilenoglicol': 'ethylene glycol',
    'glicerol': 'glycerol',
    'glicerina': 'glycerin',
    'propilenoglicol': 'propylene glycol',
    'butilenoglicol': 'butylene glycol',
    'pentilenoglicol': 'pentylene glycol',
    'sorbitol': 'sorbitol',
    'manitol': 'mannitol',
    'xilitol': 'xylitol',
    'eritritol': 'erythritol',
    'maltitol': 'maltitol',
    'lactitol': 'lactitol',
    'isomalte': 'isomalt',
    
    # ============================================
    # ÉTERES
    # ============================================
    'dimetil eter': 'dimethyl ether',
    'dietil eter': 'diethyl ether',
    'éter etílico': 'ethyl ether',
    'metil terc-butil eter': 'methyl tert-butyl ether',
    'mtbe': 'mtbe',
    'tetrahidrofurano': 'tetrahydrofuran',
    'thf': 'thf',
    'dioxano': 'dioxane',
    'furano': 'furan',
    'anisol': 'anisole',
    'fenetol': 'phenetole',
    'coroa eter': 'crown ether',
    
    # ============================================
    # ÁCIDOS
    # ============================================
    # Ácidos carboxílicos
    'acido formico': 'formic acid',
    'ácido fórmico': 'formic acid',
    'acido acetico': 'acetic acid',
    'ácido acético': 'acetic acid',
    'acido propionico': 'propionic acid',
    'ácido propiônico': 'propionic acid',
    'acido butirico': 'butyric acid',
    'ácido butírico': 'butyric acid',
    'acido valerico': 'valeric acid',
    'ácido valérico': 'valeric acid',
    'acido caproico': 'caproic acid',
    'ácido capróico': 'caproic acid',
    'acido caprilico': 'caprylic acid',
    'ácido caprílico': 'caprylic acid',
    'acido caprico': 'capric acid',
    'ácido cáprico': 'capric acid',
    'acido laurico': 'lauric acid',
    'ácido láurico': 'lauric acid',
    'acido miristico': 'myristic acid',
    'ácido mirístico': 'myristic acid',
    'acido palmitico': 'palmitic acid',
    'ácido palmítico': 'palmitic acid',
    'acido estearico': 'stearic acid',
    'ácido esteárico': 'stearic acid',
    'acido araquidico': 'arachidic acid',
    'ácido araquídico': 'arachidic acid',
    'acido behenico': 'behenic acid',
    'ácido behênico': 'behenic acid',
    'acido lignocerico': 'lignoceric acid',
    'ácido lignocérico': 'lignoceric acid',
    
    # Ácidos graxos insaturados
    'acido palmitoleico': 'palmitoleic acid',
    'ácido palmitoleico': 'palmitoleic acid',
    'acido oleico': 'oleic acid',
    'ácido oleico': 'oleic acid',
    'acido linoleico': 'linoleic acid',
    'ácido linoleico': 'linoleic acid',
    'acido linolenico': 'linolenic acid',
    'ácido linolênico': 'linolenic acid',
    'acido araquidonico': 'arachidonic acid',
    'ácido araquidônico': 'arachidonic acid',
    'acido eicosapentaenoico': 'eicosapentaenoic acid',
    'ácido eicosapentaenoico': 'eicosapentaenoic acid',
    'epa': 'epa',
    'acido docosahexaenoico': 'docosahexaenoic acid',
    'ácido docosahexaenoico': 'docosahexaenoic acid',
    'dha': 'dha',
    'acido nervonico': 'nervonic acid',
    'ácido nervônico': 'nervonic acid',
    
    # Ácidos dicarboxílicos
    'acido oxalico': 'oxalic acid',
    'ácido oxálico': 'oxalic acid',
    'acido malonico': 'malonic acid',
    'ácido malônico': 'malonic acid',
    'acido succinico': 'succinic acid',
    'ácido succínico': 'succinic acid',
    'acido glutarico': 'glutaric acid',
    'ácido glutárico': 'glutaric acid',
    'acido adipico': 'adipic acid',
    'ácido adípico': 'adipic acid',
    'acido pimelico': 'pimelic acid',
    'ácido pimélico': 'pimelic acid',
    'acido suberico': 'suberic acid',
    'ácido sobérico': 'suberic acid',
    'acido azelaico': 'azelaic acid',
    'ácido azelaico': 'azelaic acid',
    'acido sebacico': 'sebacic acid',
    'ácido sebácico': 'sebacic acid',
    'acido maleico': 'maleic acid',
    'ácido maleico': 'maleic acid',
    'acido fumarico': 'fumaric acid',
    'ácido fumárico': 'fumaric acid',
    'acido ftalico': 'phthalic acid',
    'ácido ftálico': 'phthalic acid',
    'acido isoftalico': 'isophthalic acid',
    'ácido isoftálico': 'isophthalic acid',
    'acido tereftalico': 'terephthalic acid',
    'ácido tereftálico': 'terephthalic acid',
    
    # Ácidos inorgânicos
    'acido sulfurico': 'sulfuric acid',
    'ácido sulfúrico': 'sulfuric acid',
    'acido cloridrico': 'hydrochloric acid',
    'ácido clorídrico': 'hydrochloric acid',
    'acido nitrico': 'nitric acid',
    'ácido nítrico': 'nitric acid',
    'acido fosforico': 'phosphoric acid',
    'ácido fosfórico': 'phosphoric acid',
    'acido carbonico': 'carbonic acid',
    'ácido carbônico': 'carbonic acid',
    'acido borico': 'boric acid',
    'ácido bórico': 'boric acid',
    'acido fluoridrico': 'hydrofluoric acid',
    'ácido fluorídrico': 'hydrofluoric acid',
    'acido bromidrico': 'hydrobromic acid',
    'ácido bromídrico': 'hydrobromic acid',
    'acido iodidrico': 'hydroiodic acid',
    'ácido iodídrico': 'hydroiodic acid',
    'acido perclorico': 'perchloric acid',
    'ácido perclórico': 'perchloric acid',
    'acido cloroso': 'chlorous acid',
    'ácido cloroso': 'chlorous acid',
    'acido hipocloroso': 'hypochlorous acid',
    'ácido hipocloroso': 'hypochlorous acid',
    'acido cianidrico': 'hydrocyanic acid',
    'ácido cianídrico': 'hydrocyanic acid',
    'acido fosforoso': 'phosphorous acid',
    'ácido fosforoso': 'phosphorous acid',
    'acido hipofosforoso': 'hypophosphorous acid',
    'ácido hipofosforoso': 'hypophosphorous acid',
    'acido pirofosforico': 'pyrophosphoric acid',
    'ácido pirofosfórico': 'pyrophosphoric acid',
    
    # Ácidos orgânicos diversos
    'acido citrico': 'citric acid',
    'ácido cítrico': 'citric acid',
    'acido lactico': 'lactic acid',
    'ácido lático': 'lactic acid',
    'acido malico': 'malic acid',
    'ácido málico': 'malic acid',
    'acido tartarico': 'tartaric acid',
    'ácido tartárico': 'tartaric acid',
    'acido oxalico': 'oxalic acid',
    'ácido oxálico': 'oxalic acid',
    'acido ascorbico': 'ascorbic acid',
    'ácido ascórbico': 'ascorbic acid',
    'acido fólico': 'folic acid',
    'ácido fólico': 'folic acid',
    'acido pantotenico': 'pantothenic acid',
    'ácido pantotênico': 'pantothenic acid',
    'acido biotinico': 'biotin',
    'ácido biotínico': 'biotin',
    'acido retinoico': 'retinoic acid',
    'ácido retinóico': 'retinoic acid',
    'acido glicolico': 'glycolic acid',
    'ácido glicólico': 'glycolic acid',
    'acido gluconico': 'gluconic acid',
    'ácido glucônico': 'gluconic acid',
    'acido glucuronico': 'glucuronic acid',
    'ácido glucurônico': 'glucuronic acid',
    'acido hialuronico': 'hyaluronic acid',
    'ácido hialurônico': 'hyaluronic acid',
    
    # ============================================
    # BASES E SAIS
    # ============================================
    # Hidróxidos
    'hidroxido de sodio': 'sodium hydroxide',
    'hidróxido de sódio': 'sodium hydroxide',
    'hidroxido de potassio': 'potassium hydroxide',
    'hidróxido de potássio': 'potassium hydroxide',
    'hidroxido de calcio': 'calcium hydroxide',
    'hidróxido de cálcio': 'calcium hydroxide',
    'hidroxido de aluminio': 'aluminum hydroxide',
    'hidróxido de alumínio': 'aluminum hydroxide',
    'hidroxido de magnesio': 'magnesium hydroxide',
    'hidróxido de magnésio': 'magnesium hydroxide',
    'hidroxido de litio': 'lithium hydroxide',
    'hidróxido de lítio': 'lithium hydroxide',
    'hidroxido de bario': 'barium hydroxide',
    'hidróxido de bário': 'barium hydroxide',
    'hidroxido de amonio': 'ammonium hydroxide',
    'hidróxido de amônio': 'ammonium hydroxide',
    
    # Cloretos
    'cloreto de sodio': 'sodium chloride',
    'cloreto de sódio': 'sodium chloride',
    'cloreto de potassio': 'potassium chloride',
    'cloreto de potássio': 'potassium chloride',
    'cloreto de calcio': 'calcium chloride',
    'cloreto de cálcio': 'calcium chloride',
    'cloreto de magnesio': 'magnesium chloride',
    'cloreto de magnésio': 'magnesium chloride',
    'cloreto de litio': 'lithium chloride',
    'cloreto de lítio': 'lithium chloride',
    'cloreto de bario': 'barium chloride',
    'cloreto de bário': 'barium chloride',
    'cloreto de aluminio': 'aluminum chloride',
    'cloreto de alumínio': 'aluminum chloride',
    'cloreto de ferro': 'iron chloride',
    'cloreto de ferro ii': 'iron ii chloride',
    'cloreto de ferro iii': 'iron iii chloride',
    'cloreto de mercurio': 'mercury chloride',
    'cloreto de prata': 'silver chloride',
    'cloreto de zinco': 'zinc chloride',
    'cloreto de amonio': 'ammonium chloride',
    'cloreto de amônio': 'ammonium chloride',
    
    # Carbonatos
    'carbonato de sodio': 'sodium carbonate',
    'carbonato de sódio': 'sodium carbonate',
    'carbonato de calcio': 'calcium carbonate',
    'carbonato de cálcio': 'calcium carbonate',
    'carbonato de potassio': 'potassium carbonate',
    'carbonato de potássio': 'potassium carbonate',
    'carbonato de magnesio': 'magnesium carbonate',
    'carbonato de magnésio': 'magnesium carbonate',
    'carbonato de litio': 'lithium carbonate',
    'carbonato de lítio': 'lithium carbonate',
    'carbonato de bario': 'barium carbonate',
    'carbonato de bário': 'barium carbonate',
    'carbonato de ferro': 'iron carbonate',
    
    # Bicarbonatos
    'bicarbonato de sodio': 'sodium bicarbonate',
    'bicarbonato de sódio': 'sodium bicarbonate',
    'bicarbonato de potassio': 'potassium bicarbonate',
    'bicarbonato de potássio': 'potassium bicarbonate',
    'bicarbonato de calcio': 'calcium bicarbonate',
    'bicarbonato de cálcio': 'calcium bicarbonate',
    'bicarbonato de magnesio': 'magnesium bicarbonate',
    'bicarbonato de magnésio': 'magnesium bicarbonate',
    
    # Sulfatos
    'sulfato de sodio': 'sodium sulfate',
    'sulfato de sódio': 'sodium sulfate',
    'sulfato de calcio': 'calcium sulfate',
    'sulfato de cálcio': 'calcium sulfate',
    'sulfato de magnesio': 'magnesium sulfate',
    'sulfato de magnésio': 'magnesium sulfate',
    'sulfato de potassio': 'potassium sulfate',
    'sulfato de potássio': 'potassium sulfate',
    'sulfato de cobre': 'copper sulfate',
    'sulfato de cobre ii': 'copper ii sulfate',
    'sulfato de ferro': 'iron sulfate',
    'sulfato de ferro ii': 'iron ii sulfate',
    'sulfato de ferro iii': 'iron iii sulfate',
    'sulfato de aluminio': 'aluminum sulfate',
    'sulfato de alumínio': 'aluminum sulfate',
    'sulfato de zinco': 'zinc sulfate',
    'sulfato de bario': 'barium sulfate',
    'sulfato de bário': 'barium sulfate',
    
    # Nitratos
    'nitrato de sodio': 'sodium nitrate',
    'nitrato de sódio': 'sodium nitrate',
    'nitrato de potassio': 'potassium nitrate',
    'nitrato de potássio': 'potassium nitrate',
    'nitrato de calcio': 'calcium nitrate',
    'nitrato de cálcio': 'calcium nitrate',
    'nitrato de magnesio': 'magnesium nitrate',
    'nitrato de magnésio': 'magnesium nitrate',
    'nitrato de amonio': 'ammonium nitrate',
    'nitrato de amônio': 'ammonium nitrate',
    'nitrato de prata': 'silver nitrate',
    'nitrato de bario': 'barium nitrate',
    'nitrato de bário': 'barium nitrate',
    
    # Fosfatos
    'fosfato de sodio': 'sodium phosphate',
    'fosfato de sódio': 'sodium phosphate',
    'fosfato de calcio': 'calcium phosphate',
    'fosfato de cálcio': 'calcium phosphate',
    'fosfato de potassio': 'potassium phosphate',
    'fosfato de potássio': 'potassium phosphate',
    'fosfato de amonio': 'ammonium phosphate',
    'fosfato de amônio': 'ammonium phosphate',
    'fosfato de magnesio': 'magnesium phosphate',
    'fosfato de magnésio': 'magnesium phosphate',
    'fosfato de ferro': 'iron phosphate',
    
    # Óxidos
    'oxido de sodio': 'sodium oxide',
    'óxido de sódio': 'sodium oxide',
    'oxido de calcio': 'calcium oxide',
    'óxido de cálcio': 'calcium oxide',
    'oxido de magnesio': 'magnesium oxide',
    'óxido de magnésio': 'magnesium oxide',
    'oxido de aluminio': 'aluminum oxide',
    'óxido de alumínio': 'aluminum oxide',
    'oxido de ferro': 'iron oxide',
    'óxido de ferro': 'iron oxide',
    'oxido de ferro ii': 'iron ii oxide',
    'óxido de ferro ii': 'iron ii oxide',
    'oxido de ferro iii': 'iron iii oxide',
    'óxido de ferro iii': 'iron iii oxide',
    'oxido de zinco': 'zinc oxide',
    'óxido de zinco': 'zinc oxide',
    'oxido de titanio': 'titanium oxide',
    'óxido de titânio': 'titanium oxide',
    'dioxido de titanio': 'titanium dioxide',
    'dióxido de titânio': 'titanium dioxide',
    'dioxido de silicio': 'silicon dioxide',
    'dióxido de silício': 'silicon dioxide',
    'sílica': 'silica',
    
    'dioxido de carbono': 'carbon dioxide',
    'dióxido de carbono': 'carbon dioxide',
    'monoxido de carbono': 'carbon monoxide',
    'monóxido de carbono': 'carbon monoxide',
    'dioxido de enxofre': 'sulfur dioxide',
    'dióxido de enxofre': 'sulfur dioxide',
    'trioxido de enxofre': 'sulfur trioxide',
    'trióxido de enxofre': 'sulfur trioxide',
    'monoxido de nitrogenio': 'nitric oxide',
    'monóxido de nitrogênio': 'nitric oxide',
    'dioxido de nitrogenio': 'nitrogen dioxide',
    'dióxido de nitrogênio': 'nitrogen dioxide',
    'protóxido de nitrogenio': 'nitrous oxide',
    'protóxido de nitrogênio': 'nitrous oxide',
    'peroxido de hidrogenio': 'hydrogen peroxide',
    'peróxido de hidrogênio': 'hydrogen peroxide',
    
    # ============================================
    # ELEMENTOS QUÍMICOS (Tabela Periódica)
    # ============================================
    # Não-metais
    'hidrogenio': 'hydrogen',
    'hidrogênio': 'hydrogen',
    'helio': 'helium',
    'hélio': 'helium',
    'litio': 'lithium',
    'lítio': 'lithium',
    'berilio': 'beryllium',
    'berílio': 'beryllium',
    'boro': 'boron',
    'carbono': 'carbon',
    'nitrogenio': 'nitrogen',
    'nitrogênio': 'nitrogen',
    'oxigenio': 'oxygen',
    'oxigênio': 'oxygen',
    'fluor': 'fluorine',
    'flúor': 'fluorine',
    'neonio': 'neon',
    'neônio': 'neon',
    'sodio': 'sodium',
    'sódio': 'sodium',
    'magnesio': 'magnesium',
    'magnésio': 'magnesium',
    'aluminio': 'aluminum',
    'alumínio': 'aluminum',
    'silicio': 'silicon',
    'silício': 'silicon',
    'fosforo': 'phosphorus',
    'fósforo': 'phosphorus',
    'enxofre': 'sulfur',
    'cloro': 'chlorine',
    'argonio': 'argon',
    'argônio': 'argon',
    'potassio': 'potassium',
    'potássio': 'potassium',
    'calcio': 'calcium',
    'cálcio': 'calcium',
    'escandio': 'scandium',
    'escândio': 'scandium',
    'titânio': 'titanium',
    'vanadio': 'vanadium',
    'vanádio': 'vanadium',
    'cromo': 'chromium',
    'manganes': 'manganese',
    'manganês': 'manganese',
    'ferro': 'iron',
    'cobalto': 'cobalt',
    'niquel': 'nickel',
    'níquel': 'nickel',
    'cobre': 'copper',
    'zinco': 'zinc',
    'galio': 'gallium',
    'gálio': 'gallium',
    'germanio': 'germanium',
    'germânio': 'germanium',
    'arsenio': 'arsenic',
    'arsênio': 'arsenic',
    'selenio': 'selenium',
    'selênio': 'selenium',
    'bromo': 'bromine',
    'criptonio': 'krypton',
    'criptônio': 'krypton',
    'rubidio': 'rubidium',
    'rubídio': 'rubidium',
    'estroncio': 'strontium',
    'estrôncio': 'strontium',
    'itrio': 'yttrium',
    'ítrio': 'yttrium',
    'zirconio': 'zirconium',
    'zircônio': 'zirconium',
    'niobio': 'niobium',
    'nióbio': 'niobium',
    'molibdenio': 'molybdenum',
    'molibdênio': 'molybdenum',
    'tecnecio': 'technetium',
    'tecnécio': 'technetium',
    'rutenio': 'ruthenium',
    'rutênio': 'ruthenium',
    'rodio': 'rhodium',
    'ródio': 'rhodium',
    'paladio': 'palladium',
    'paládio': 'palladium',
    'prata': 'silver',
    'cadmio': 'cadmium',
    'cádmio': 'cadmium',
    'indio': 'indium',
    'índio': 'indium',
    'estanho': 'tin',
    'antimonio': 'antimony',
    'antimônio': 'antimony',
    'telurio': 'tellurium',
    'telúrio': 'tellurium',
    'iodo': 'iodine',
    'xenonio': 'xenon',
    'xenônio': 'xenon',
    'cesio': 'cesium',
    'césio': 'cesium',
    'bario': 'barium',
    'bário': 'barium',
    'lantanio': 'lanthanum',
    'lantânio': 'lanthanum',
    'cerio': 'cerium',
    'cério': 'cerium',
    'praseodimio': 'praseodymium',
    'praseodímio': 'praseodymium',
    'neodimio': 'neodymium',
    'neodímio': 'neodymium',
    'promecio': 'promethium',
    'promécio': 'promethium',
    'samario': 'samarium',
    'samário': 'samarium',
    'europio': 'europium',
    'europio': 'europium',
    'gadolinio': 'gadolinium',
    'gadolínio': 'gadolinium',
    'terbio': 'terbium',
    'terbio': 'terbium',
    'disprosio': 'dysprosium',
    'disprósio': 'dysprosium',
    'holmio': 'holmium',
    'hólmio': 'holmium',
    'erbio': 'erbium',
    'érbio': 'erbium',
    'tulio': 'thulium',
    'túlio': 'thulium',
    'iterbio': 'ytterbium',
    'itérbio': 'ytterbium',
    'lutecio': 'lutetium',
    'lutécio': 'lutetium',
    'hafnio': 'hafnium',
    'háfnio': 'hafnium',
    'tantalo': 'tantalum',
    'tântalo': 'tantalum',
    'tungstenio': 'tungsten',
    'tungstênio': 'tungsten',
    'renio': 'rhenium',
    'rênio': 'rhenium',
    'osmio': 'osmium',
    'ório': 'osmium',
    'iridio': 'iridium',
    'irídio': 'iridium',
    'platina': 'platinum',
    'ouro': 'gold',
    'mercurio': 'mercury',
    'mercúrio': 'mercury',
    'talio': 'thallium',
    'tálio': 'thallium',
    'chumbo': 'lead',
    'bismuto': 'bismuth',
    'polonio': 'polonium',
    'polônio': 'polonium',
    'astato': 'astatine',
    'radonio': 'radon',
    'radônio': 'radon',
    'francio': 'francium',
    'frâncio': 'francium',
    'radio': 'radium',
    'rádio': 'radium',
    'actinio': 'actinium',
    'actínio': 'actinium',
    'torio': 'thorium',
    'tório': 'thorium',
    'protactinio': 'protactinium',
    'protactínio': 'protactinium',
    'uranio': 'uranium',
    'urânio': 'uranium',
    'netunio': 'neptunium',
    'netúnio': 'neptunium',
    'plutonio': 'plutonium',
    'plutônio': 'plutonium',
    'americio': 'americium',
    'amerício': 'americium',
    'curio': 'curium',
    'cúrio': 'curium',
    'berkelio': 'berkelium',
    'berkélio': 'berkelium',
    'californio': 'californium',
    'califórnio': 'californium',
    'einstenio': 'einsteinium',
    'einstênio': 'einsteinium',
    'fermio': 'fermium',
    'férmio': 'fermium',
    'mendelevio': 'mendelevium',
    'mendelévio': 'mendelevium',
    'nobelio': 'nobelium',
    'nobélio': 'nobelium',
    'laurencio': 'lawrencium',
    'laurêncio': 'lawrencium',
    'rutherfordio': 'rutherfordium',
    'rutherfórdio': 'rutherfordium',
    'dubnio': 'dubnium',
    'seaborgio': 'seaborgium',
    'seabórgio': 'seaborgium',
    'bohrio': 'bohrium',
    'bóhrio': 'bohrium',
    'hassio': 'hassium',
    'hássio': 'hassium',
    'meitnerio': 'meitnerium',
    'meitnério': 'meitnerium',
    'darmstadcio': 'darmstadtium',
    'darmstádtio': 'darmstadtium',
    'roentgenio': 'roentgenium',
    'roentgênio': 'roentgenium',
    'copernicio': 'copernicium',
    'copernício': 'copernicium',
    'nihonio': 'nihonium',
    'nihônio': 'nihonium',
    'flerovio': 'flerovium',
    'fleróvio': 'flerovium',
    'moscovio': 'moscovium',
    'moscóvio': 'moscovium',
    'livermorio': 'livermorium',
    'livermório': 'livermorium',
    'tennessine': 'tennessine',
    'oganesson': 'oganesson',
    
    # ============================================
    # AÇÚCARES E CARBOIDRATOS
    # ============================================
    'glicose': 'glucose',
    'dextrose': 'dextrose',
    'frutose': 'fructose',
    'sacarose': 'sucrose',
    'açúcar': 'sucrose',
    'acucar': 'sucrose',
    'maltose': 'maltose',
    'lactose': 'lactose',
    'lactulose': 'lactulose',
    'galactose': 'galactose',
    'ribose': 'ribose',
    'desoxirribose': 'deoxyribose',
    'xilose': 'xylose',
    'arabinose': 'arabinose',
    'manose': 'mannose',
    'ramnose': 'rhamnose',
    'fucose': 'fucose',
    'trealose': 'trehalose',
    'raffinose': 'raffinose',
    'estaquiose': 'stachyose',
    'amido': 'starch',
    'amido resistente': 'resistant starch',
    'celulose': 'cellulose',
    'celulose microcristalina': 'microcrystalline cellulose',
    'hemicelulose': 'hemicellulose',
    'lignina': 'lignin',
    'pectina': 'pectin',
    'goma': 'gum',
    'goma xantana': 'xanthan gum',
    'goma guar': 'guar gum',
    'goma arábica': 'gum arabic',
    'goma gelana': 'gellan gum',
    'goma carragena': 'carrageenan',
    'agar': 'agar',
    'agarose': 'agarose',
    'glicogenio': 'glycogen',
    'glicogênio': 'glycogen',
    'quitina': 'chitin',
    'quitosana': 'chitosan',
    'dextrina': 'dextrin',
    'maltodextrina': 'maltodextrin',
    'inulina': 'inulin',
    'frutooligossacarideo': 'fructooligosaccharide',
    'galactooligossacarideo': 'galactooligosaccharide',
    
    # ============================================
    # SOLVENTES E COMPOSTOS ORGÂNICOS COMUNS
    # ============================================
    'agua': 'water',
    'água': 'water',
    'agua destilada': 'distilled water',
    'água destilada': 'distilled water',
    'agua deionizada': 'deionized water',
    'água deionizada': 'deionized water',
    'agua milli-q': 'milli-q water',
    'água milli-q': 'milli-q water',
    'amonia': 'ammonia',
    'amônia': 'ammonia',
    'acetona': 'acetone',
    'acetonitrila': 'acetonitrile',
    'ureia': 'urea',
    'uréia': 'urea',
    'cloroformio': 'chloroform',
    'clorofórmio': 'chloroform',
    'diclorometano': 'dichloromethane',
    'cloreto de metileno': 'methylene chloride',
    'tetracloreto de carbono': 'carbon tetrachloride',
    'eter': 'ether',
    'éter': 'ether',
    'dietil eter': 'diethyl ether',
    'éter dietílico': 'diethyl ether',
    'dimetilformamida': 'dimethylformamide',
    'dmf': 'dmf',
    'dimethyl sulfoxide': 'dimethyl sulfoxide',
    'dmso': 'dmso',
    'tetrahidrofurano': 'tetrahydrofuran',
    'thf': 'thf',
    'hexano': 'hexane',
    'ciclohexano': 'cyclohexane',
    'heptano': 'heptane',
    'tolueno': 'toluene',
    'xileno': 'xylene',
    'benzeno': 'benzene',
    'piridina': 'pyridine',
    'trietilamina': 'triethylamine',
    'tea': 'tea',
    'dietilamina': 'diethylamine',
    'monoetanolamina': 'monoethanolamine',
    'mea': 'mea',
    'dietanolamina': 'diethanolamine',
    'dea': 'dea',
    'trietanolamina': 'triethanolamine',
    'tea': 'tea',
    'etilenoglicol': 'ethylene glycol',
    'propilenoglicol': 'propylene glycol',
    'glicerol': 'glycerol',
    'glicerina': 'glycerin',
    
    # ============================================
    # GASES
    # ============================================
    'hidrogenio': 'hydrogen',
    'hidrogênio': 'hydrogen',
    'oxigenio': 'oxygen',
    'oxigênio': 'oxygen',
    'ozonio': 'ozone',
    'ozônio': 'ozone',
    'nitrogenio': 'nitrogen',
    'nitrogênio': 'nitrogen',
    'dioxido de carbono': 'carbon dioxide',
    'dióxido de carbono': 'carbon dioxide',
    'monoxido de carbono': 'carbon monoxide',
    'monóxido de carbono': 'carbon monoxide',
    'metano': 'methane',
    'etano': 'ethane',
    'propano': 'propane',
    'butano': 'butane',
    'gás natural': 'natural gas',
    'glp': 'lpg',
    'gás liquefeito de petroleo': 'liquefied petroleum gas',
    'gás liquefeito de petróleo': 'liquefied petroleum gas',
    'cloro': 'chlorine',
    'cloro gasoso': 'chlorine gas',
    'fluor': 'fluorine',
    'flúor': 'fluorine',
    'bromo': 'bromine',
    'iodo': 'iodine',
    'argonio': 'argon',
    'argônio': 'argon',
    'helio': 'helium',
    'hélio': 'helium',
    'neonio': 'neon',
    'neônio': 'neon',
    'criptonio': 'krypton',
    'criptônio': 'krypton',
    'xenonio': 'xenon',
    'xenônio': 'xenon',
    'radonio': 'radon',
    'radônio': 'radon',
    'dioxido de enxofre': 'sulfur dioxide',
    'dióxido de enxofre': 'sulfur dioxide',
    'trioxido de enxofre': 'sulfur trioxide',
    'trióxido de enxofre': 'sulfur trioxide',
    'sulfeto de hidrogenio': 'hydrogen sulfide',
    'sulfeto de hidrogênio': 'hydrogen sulfide',
    'gás sulfidrico': 'hydrogen sulfide',
    'gás sulfídrico': 'hydrogen sulfide',
    'amonia': 'ammonia',
    'amônia': 'ammonia',
    'cloreto de hidrogenio': 'hydrogen chloride',
    'cloreto de hidrogênio': 'hydrogen chloride',
    'gás cloridrico': 'hydrogen chloride',
    'gás clorídrico': 'hydrogen chloride',
    'fosfina': 'phosphine',
    'arsina': 'arsine',
    'silan': 'silane',
    'gás de síntese': 'syngas',
    'gás de xisto': 'shale gas',
    'biogas': 'biogas',
    'biogás': 'biogas',
    
    # ============================================
    # FÁRMACOS E MEDICAMENTOS
    # ============================================
    'aspirina': 'aspirin',
    'acido acetilsalicilico': 'acetylsalicylic acid',
    'ácido acetilsalicílico': 'acetylsalicylic acid',
    'paracetamol': 'acetaminophen',
    'acetaminofeno': 'acetaminophen',
    'ibuprofeno': 'ibuprofen',
    'naproxeno': 'naproxen',
    'diclofenaco': 'diclofenac',
    'cetoprofeno': 'ketoprofen',
    'indometacina': 'indomethacin',
    'celecoxibe': 'celecoxib',
    'dipirona': 'dipyrone',
    'metamizol': 'metamizole',
    
    'amoxicilina': 'amoxicillin',
    'ampicilina': 'ampicillin',
    'penicilina': 'penicillin',
    'cefalexina': 'cephalexin',
    'ceftriaxona': 'ceftriaxone',
    'azitromicina': 'azithromycin',
    'claritromicina': 'clarithromycin',
    'eritromicina': 'erythromycin',
    'tetraciclina': 'tetracycline',
    'doxiciclina': 'doxycycline',
    'ciprofloxacino': 'ciprofloxacin',
    'levofloxacino': 'levofloxacin',
    'moxifloxacino': 'moxifloxacin',
    'metronidazol': 'metronidazole',
    'vancomicina': 'vancomycin',
    'teicoplanina': 'teicoplanin',
    'polimixina': 'polymyxin',
    
    'cafeina': 'caffeine',
    'cafeína': 'caffeine',
    'nicotina': 'nicotine',
    'morfina': 'morphine',
    'codeina': 'codeine',
    'codeína': 'codeine',
    'heroina': 'heroin',
    'heroína': 'heroin',
    'cocaina': 'cocaine',
    'cocaína': 'cocaine',
    'anfetamina': 'amphetamine',
    'metanfetamina': 'methamphetamine',
    'mdma': 'mdma',
    'ecstasy': 'ecstasy',
    'lsd': 'lsd',
    'dietilamida do acido lisergico': 'lysergic acid diethylamide',
    'dietilamida do ácido lisérgico': 'lysergic acid diethylamide',
    'thc': 'thc',
    'tetrahidrocanabinol': 'tetrahydrocannabinol',
    'canabidiol': 'cannabidiol',
    'cbd': 'cbd',
    
    'diazepam': 'diazepam',
    'lorazepam': 'lorazepam',
    'alprazolam': 'alprazolam',
    'clonazepam': 'clonazepam',
    'bromazepam': 'bromazepam',
    'fluoxetina': 'fluoxetine',
    'sertralina': 'sertraline',
    'paroxetina': 'paroxetine',
    'citalopram': 'citalopram',
    'escitalopram': 'escitalopram',
    
    'omeprazol': 'omeprazole',
    'esomeprazol': 'esomeprazole',
    'pantoprazol': 'pantoprazole',
    'lansoprazol': 'lansoprazole',
    'rabeprazol': 'rabeprazole',
    
    'losartan': 'losartan',
    'valsartan': 'valsartan',
    'candesartan': 'candesartan',
    'irbesartan': 'irbesartan',
    'enalapril': 'enalapril',
    'lisinopril': 'lisinopril',
    'captopril': 'captopril',
    'ramipril': 'ramipril',
    
    'simvastatina': 'simvastatin',
    'atorvastatina': 'atorvastatin',
    'rosuvastatina': 'rosuvastatin',
    'pravastatina': 'pravastatin',
    'lovastatina': 'lovastatin',
    
    'metformina': 'metformin',
    'glibenclamida': 'glibenclamide',
    'glimepirida': 'glimepiride',
    'glipizida': 'glipizide',
    'insulina': 'insulin',
    'insulina regular': 'regular insulin',
    'insulina nph': 'nph insulin',
    'insulina glargina': 'insulin glargine',
    'insulina detemir': 'insulin detemir',
    'insulina aspart': 'insulin aspart',
    'insulina lispro': 'insulin lispro',
    
    'levotiroxina': 'levothyroxine',
    'metimazol': 'methimazole',
    'propiltiouracil': 'propylthiouracil',
    
    'prednisona': 'prednisone',
    'prednisolona': 'prednisolone',
    'dexametasona': 'dexamethasone',
    'hidrocortisona': 'hydrocortisone',
    'metilprednisolona': 'methylprednisolone',
    'betametasona': 'betamethasone',
    
    'alopurinol': 'allopurinol',
    'colchicina': 'colchicine',
    'probenecida': 'probenecid',
    
    # ============================================
    # VITAMINAS
    # ============================================
    'vitamina a': 'vitamin a',
    'retinol': 'retinol',
    'retinal': 'retinal',
    'acido retinoico': 'retinoic acid',
    'ácido retinóico': 'retinoic acid',
    'beta-caroteno': 'beta-carotene',
    
    'vitamina b1': 'vitamin b1',
    'tiamina': 'thiamine',
    
    'vitamina b2': 'vitamin b2',
    'riboflavina': 'riboflavin',
    
    'vitamina b3': 'vitamin b3',
    'niacina': 'niacin',
    'nicotinamida': 'nicotinamide',
    'niacinamida': 'niacinamide',
    
    'vitamina b5': 'vitamin b5',
    'acido pantotenico': 'pantothenic acid',
    'ácido pantotênico': 'pantothenic acid',
    'pantenol': 'panthenol',
    
    'vitamina b6': 'vitamin b6',
    'piridoxina': 'pyridoxine',
    'piridoxal': 'pyridoxal',
    'piridoxamina': 'pyridoxamine',
    
    'vitamina b7': 'vitamin b7',
    'biotina': 'biotin',
    'vitamina h': 'vitamin h',
    
    'vitamina b9': 'vitamin b9',
    'acido folico': 'folic acid',
    'ácido fólico': 'folic acid',
    'folato': 'folate',
    'folacina': 'folacin',
    
    'vitamina b12': 'vitamin b12',
    'cobalamina': 'cobalamin',
    'cianocobalamina': 'cyanocobalamin',
    'metilcobalamina': 'methylcobalamin',
    
    'vitamina c': 'vitamin c',
    'acido ascorbico': 'ascorbic acid',
    'ácido ascórbico': 'ascorbic acid',
    
    'vitamina d': 'vitamin d',
    'colecalciferol': 'cholecalciferol',
    'vitamina d3': 'vitamin d3',
    'ergocalciferol': 'ergocalciferol',
    'vitamina d2': 'vitamin d2',
    'calcitriol': 'calcitriol',
    
    'vitamina e': 'vitamin e',
    'tocoferol': 'tocopherol',
    'tocotrienol': 'tocotrienol',
    'alfa-tocoferol': 'alpha-tocopherol',
    
    'vitamina k': 'vitamin k',
    'filoquinona': 'phylloquinone',
    'vitamina k1': 'vitamin k1',
    'menaquinona': 'menaquinone',
    'vitamina k2': 'vitamin k2',
    'menadiona': 'menadione',
    'vitamina k3': 'vitamin k3',
    
    # ============================================
    # HORMÔNIOS
    # ============================================
    'testosterona': 'testosterone',
    'estrogenio': 'estrogen',
    'estrogênio': 'estrogen',
    'estradiol': 'estradiol',
    'estriol': 'estriol',
    'estrona': 'estrone',
    'progesterona': 'progesterone',
    'cortisol': 'cortisol',
    'hidrocortisona': 'hydrocortisone',
    'cortisona': 'cortisone',
    'aldosterona': 'aldosterone',
    'adrenalina': 'epinephrine',
    'adrenalina': 'adrenaline',
    'epinefrina': 'epinephrine',
    'noradrenalina': 'norepinephrine',
    'noradrenalina': 'noradrenaline',
    'norepinefrina': 'norepinephrine',
    'dopamina': 'dopamine',
    'serotonina': 'serotonin',
    'melatonina': 'melatonin',
    'tiroxina': 'thyroxine',
    't4': 't4',
    'triiodotironina': 'triiodothyronine',
    't3': 't3',
    'calcitonina': 'calcitonin',
    'paratormonio': 'parathyroid hormone',
    'pth': 'pth',
    'insulina': 'insulin',
    'glucagon': 'glucagon',
    'leptina': 'leptin',
    'grelina': 'ghrelin',
    'crescimento': 'growth hormone',
    'gh': 'gh',
    'hormonio do crescimento': 'growth hormone',
    'prolactina': 'prolactin',
    'ocitocina': 'oxytocin',
    'vasopressina': 'vasopressin',
    'adh': 'adh',
    'angiotensina': 'angiotensin',
    'eritropoietina': 'erythropoietin',
    'epo': 'epo',
    
    # ============================================
    # AMINOÁCIDOS
    # ============================================
    'alanina': 'alanine',
    'arginina': 'arginine',
    'asparagina': 'asparagine',
    'acido aspartico': 'aspartic acid',
    'ácido aspártico': 'aspartic acid',
    'cisteina': 'cysteine',
    'cisteína': 'cysteine',
    'cistina': 'cystine',
    'glutamina': 'glutamine',
    'acido glutamico': 'glutamic acid',
    'ácido glutâmico': 'glutamic acid',
    'glutamato': 'glutamate',
    'glicina': 'glycine',
    'histidina': 'histidine',
    'isoleucina': 'isoleucine',
    'leucina': 'leucine',
    'lisina': 'lysine',
    'metionina': 'methionine',
    'fenilalanina': 'phenylalanine',
    'prolina': 'proline',
    'hidroxiprolina': 'hydroxyproline',
    'serina': 'serine',
    'treonina': 'threonine',
    'triptofano': 'tryptophan',
    'tirosina': 'tyrosine',
    'valina': 'valine',
    'selenocisteina': 'selenocysteine',
    'pirrolisina': 'pyrrolysine',
    
    # ============================================
    # NEUROTRANSMISSORES
    # ============================================
    'acetilcolina': 'acetylcholine',
    'gaba': 'gaba',
    'acido gama-aminobutirico': 'gamma-aminobutyric acid',
    'ácido gama-aminobutírico': 'gamma-aminobutyric acid',
    'glutamato': 'glutamate',
    'aspartato': 'aspartate',
    'glicina': 'glycine',
    'taurina': 'taurine',
    'histamina': 'histamine',
    'serotonina': 'serotonin',
    'dopamina': 'dopamine',
    'noradrenalina': 'norepinephrine',
    'adrenalina': 'epinephrine',
    'anandamida': 'anandamide',
    'endorfina': 'endorphin',
    'encefalina': 'enkephalin',
    'dinorfina': 'dynorphin',
    'noceptina': 'nociceptin',
    
    # ============================================
    # PIGMENTOS E CORANTES
    # ============================================
    'clorofila': 'chlorophyll',
    'clorofila a': 'chlorophyll a',
    'clorofila b': 'chlorophyll b',
    'hemoglobina': 'hemoglobin',
    'hemoglobina humana': 'hemoglobin',
    'mioglobina': 'myoglobin',
    'bilirrubina': 'bilirubin',
    'biliverdina': 'biliverdin',
    'melanina': 'melanin',
    'eumelanina': 'eumelanin',
    'feomelanina': 'pheomelanin',
    'caroteno': 'carotene',
    'beta-caroteno': 'beta-carotene',
    'alfa-caroteno': 'alpha-carotene',
    'licopeno': 'lycopene',
    'luteina': 'lutein',
    'zeaxantina': 'zeaxanthin',
    'astaxantina': 'astaxanthin',
    'cantaxantina': 'canthaxanthin',
    'antocianina': 'anthocyanin',
    'cianidina': 'cyanidin',
    'delfinidina': 'delphinidin',
    'pelargonidina': 'pelargonidin',
    'peonidina': 'peonidin',
    'petunidina': 'petunidin',
    'malvidina': 'malvidin',
    'flavonoide': 'flavonoid',
    'flavonol': 'flavonol',
    'quercetina': 'quercetin',
    'kaempferol': 'kaempferol',
    'miricetina': 'myricetin',
    'rutina': 'rutin',
    'catequina': 'catechin',
    'epicatequina': 'epicatechin',
    'teofilina': 'theophylline',
    'teobromina': 'theobromine',
    'curcumina': 'curcumin',
    'tumeric': 'turmeric',
    'açafrão': 'saffron',
    'açafrao': 'saffron',
    
    # ============================================
    # POLÍMEROS E PLÁSTICOS
    # ============================================
    'polietileno': 'polyethylene',
    'pe': 'pe',
    'polietileno de alta densidade': 'high density polyethylene',
    'pead': 'hdpe',
    'polietileno de baixa densidade': 'low density polyethylene',
    'pebd': 'ldpe',
    'polietileno linear de baixa densidade': 'linear low density polyethylene',
    'pebdl': 'lldpe',
    
    'polipropileno': 'polypropylene',
    'pp': 'pp',
    
    'pvc': 'pvc',
    'policloreto de vinila': 'polyvinyl chloride',
    'cloreto de polivinila': 'polyvinyl chloride',
    
    'poliestireno': 'polystyrene',
    'ps': 'ps',
    'espuma de poliestireno': 'polystyrene foam',
    'isopor': 'styrofoam',
    
    'teflon': 'teflon',
    'politetrafluoretileno': 'polytetrafluoroethylene',
    'ptfe': 'ptfe',
    
    'nylon': 'nylon',
    'poliamida': 'polyamide',
    'pa': 'pa',
    
    'poliuretano': 'polyurethane',
    'pu': 'pu',
    
    'policarbonato': 'polycarbonate',
    'pc': 'pc',
    
    'pet': 'pet',
    'politereftalato de etileno': 'polyethylene terephthalate',
    'poli(tereftalato de etileno)': 'poly(ethylene terephthalate)',
    
    'poli(acido latico)': 'polylactic acid',
    'pla': 'pla',
    
    'poli(acido glicolico)': 'polyglycolic acid',
    'pga': 'pga',
    
    'poli(hidroxialcanoato)': 'polyhydroxyalkanoate',
    'pha': 'pha',
    
    'poli(caprolactona)': 'polycaprolactone',
    'pcl': 'pcl',
    
    'borracha': 'rubber',
    'borracha natural': 'natural rubber',
    'poliisopreno': 'polyisoprene',
    'neoprene': 'neoprene',
    'policloropreno': 'polychloroprene',
    'silicone': 'silicone',
    
    # ============================================
    # DETERGENTES E TENSORATIVOS
    # ============================================
    'sds': 'sds',
    'sodium dodecyl sulfate': 'sds',
    'sodio dodecil sulfato': 'sodium dodecyl sulfate',
    'sódio dodecil sulfato': 'sodium dodecyl sulfate',
    'triton': 'triton',
    'triton x-100': 'triton x-100',
    'tween': 'tween',
    'tween 20': 'tween 20',
    'tween 80': 'tween 80',
    'ctab': 'ctab',
    'brometo de cetiltrimetilamonio': 'cetyltrimethylammonium bromide',
    'brometo de cetiltrimetilamônio': 'cetyltrimethylammonium bromide',
    'cholato': 'cholate',
    'desoxicolato': 'deoxycholate',
    'sapo': 'soap',
    'sabao': 'soap',
    'sabão': 'soap',
    'detergente': 'detergent',
    'detergente ionico': 'ionic detergent',
    'detergente nao ionico': 'non-ionic detergent',
    'detergente não iônico': 'non-ionic detergent',
    'lauroil sarcosinato': 'lauroyl sarcosinate',
    'sarkosil': 'sarkosyl',
    
    # ============================================
    # PESTICIDAS E HERBICIDAS
    # ============================================
    'glifosato': 'glyphosate',
    'roundup': 'roundup',
    'paraquat': 'paraquat',
    'diclorvós': 'dichlorvos',
    'ddvp': 'ddvp',
    'malation': 'malathion',
    'malatião': 'malathion',
    'clorpirifós': 'chlorpyrifos',
    'diazinon': 'diazinon',
    'diazinão': 'diazinon',
    'atrazina': 'atrazine',
    'diuron': 'diuron',
    'glufosinato': 'glufosinate',
    'alacloro': 'alachlor',
    'metolacloro': 'metolachlor',
    '2,4-d': '2,4-d',
    'ácido 2,4-diclorofenoxiacético': '2,4-dichlorophenoxyacetic acid',
    'dicloro difenil tricloroetano': 'dichlorodiphenyltrichloroethane',
    'ddt': 'ddt',
    
    # ============================================
    # POLUENTES AMBIENTAIS
    # ============================================
    'bifenil policlorado': 'polychlorinated biphenyl',
    'pcb': 'pcb',
    'dioxina': 'dioxin',
    'tcdd': 'tcdd',
    'furanos': 'furans',
    'pah': 'pah',
    'hidrocarboneto policiclico aromatico': 'polycyclic aromatic hydrocarbon',
    'hidrocarboneto policíclico aromático': 'polycyclic aromatic hydrocarbon',
    'hpa': 'pah',
    'pfoa': 'pfoa',
    'ácido perfluorooctanoico': 'perfluorooctanoic acid',
    'pfos': 'pfos',
    'sulfonato de perfluorooctano': 'perfluorooctane sulfonate',
    'bpa': 'bpa',
    'bisfenol a': 'bisphenol a',
    'ftalato': 'phthalate',
    'dehp': 'dehp',
    'chumbo': 'lead',
    'mercurio': 'mercury',
    'cádmio': 'cadmium',
    'arsenio': 'arsenic',
    'cromo': 'chromium',
    'cromo hexavalente': 'hexavalent chromium',
    
    # ============================================
    # COMBUSTÍVEIS E DERIVADOS
    # ============================================
    'gasolina': 'gasoline',
    'petrol': 'petrol',
    'diesel': 'diesel',
    'oleo diesel': 'diesel oil',
    'óleo diesel': 'diesel oil',
    'querosene': 'kerosene',
    'querozene': 'kerosene',
    'jet fuel': 'jet fuel',
    'avgas': 'avgas',
    'alcool': 'alcohol',
    'álcool': 'alcohol',
    'etanol combustivel': 'fuel ethanol',
    'etanol combustível': 'fuel ethanol',
    'biodiesel': 'biodiesel',
    'biocombustivel': 'biofuel',
    'biocombustível': 'biofuel',
    'metanol combustivel': 'methanol fuel',
    'metanol combustível': 'methanol fuel',
    'glp': 'lpg',
    'gnv': 'cng',
    'gás natural veicular': 'compressed natural gas',
    'glp': 'lpg',
    'gas de cozinha': 'lpg',
    'gás de cozinha': 'lpg',
    'gas de cidade': 'town gas',
    'gás de cidade': 'town gas',
    'gás de síntese': 'syngas',
    'gas de xisto': 'shale gas',
    'gás de xisto': 'shale gas',
    'oleo combustivel': 'fuel oil',
    'óleo combustível': 'fuel oil',
    'oleo cru': 'crude oil',
    'óleo cru': 'crude oil',
    'petroleo': 'petroleum',
    'petróleo': 'petroleum',
    'asfalto': 'asphalt',
    'betume': 'bitumen',
    'parafina': 'paraffin',
    'vaselina': 'petroleum jelly',
    'graxa': 'grease',
    'lubrificante': 'lubricant',
    
    # ============================================
    # CORANTES ALIMENTARES (INS)
    # ============================================
    'tartrazina': 'tartrazine',
    'fd&c amarelo 5': 'fd&c yellow 5',
    'amarelo crepúsculo': 'sunset yellow',
    'fd&c amarelo 6': 'fd&c yellow 6',
    'azorubina': 'azorubine',
    'carmoisina': 'carmoisine',
    'vermelho 40': 'red 40',
    'fd&c vermelho 40': 'fd&c red 40',
    'eritrosina': 'erythrosine',
    'fd&c vermelho 3': 'fd&c red 3',
    'azul brilhante': 'brilliant blue',
    'fd&c azul 1': 'fd&c blue 1',
    'indigotina': 'indigotine',
    'fd&c azul 2': 'fd&c blue 2',
    'verde rápido': 'fast green',
    'fd&c verde 3': 'fd&c green 3',
    'vermelho de beterraba': 'beetroot red',
    'betanina': 'betanin',

    # ============================================
    # SIGLAS E ABREVIAÇÕES (ADICIONADO)
    # ============================================
    'dna': 'deoxyribonucleic acid',
    'rna': 'ribonucleic acid',
    'mrna': 'messenger rna',
    'trna': 'transfer rna',
    'rrna': 'ribosomal rna',
    'atp': 'adenosine triphosphate',
    'adp': 'adenosine diphosphate',
    'amp': 'adenosine monophosphate',
    'camp': 'cyclic amp',
    'gtp': 'guanosine triphosphate',
    'gdp': 'guanosine diphosphate',
    'nadh': 'nadh',
    'nadph': 'nadph',
    'nad': 'nicotinamide adenine dinucleotide',
    'fad': 'flavin adenine dinucleotide',
    'coa': 'coenzyme a',
    'edta': 'edta',
    'tris': 'tris',
    'sds': 'sodium dodecyl sulfate',
    'pcr': 'polymerase chain reaction',
    'elisa': 'elisa',
    'hplc': 'high performance liquid chromatography',
    'nmr': 'nmr',
    'ms': 'mass spectrometry',
    
    # ============================================
    # NOMES COMERCIAIS COMUNS (ADICIONADO)
    # ============================================
    'tylenol': 'acetaminophen',
    'advil': 'ibuprofen',
    'motrin': 'ibuprofen',
    'aleve': 'naproxen',
    'viagra': 'sildenafil',
    'cialis': 'tadalafil',
    'prozac': 'fluoxetine',
    'zoloft': 'sertraline',
    'valium': 'diazepam',
    'xanax': 'alprazolam',
    'lipitor': 'atorvastatin',
    'crestor': 'rosuvastatin',
    'prilosec': 'omeprazole',
    'nexium': 'esomeprazole',
    'glucophage': 'metformin',
    'lantus': 'insulin glargine',
}


# Dicionário reverso (inglês -> português)
DICIONARIO_REVERSO = {v: k for k, v in DICIONARIO_QUIMICO.items()}

# Estatísticas
print(f"📊 Dicionário carregado: {len(DICIONARIO_QUIMICO)} traduções")
print(f"📊 Categorias: Alcanos, Alcenos, Alcinos, Aromáticos, Álcools, Ácidos, Bases, Elementos, Fármacos, Vitaminas, Hormônios, Aminoácidos, Polímeros, e mais!")